Temporarily disable Octave and R actifacts

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -179,191 +179,191 @@ jobs:
           path: |
             dist 
             
-  build-octave-package:
-    needs: check-release-consistency    
-    runs-on: ${{ matrix.os }}
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-          - name: "Octave Linux"
-            os: ubuntu-22.04 # required to ease the support of octave ≥ 6
-            force_update: on
-          - name: "Octave macOS"
-            os: macOS-12
-          - name: "Octave Windows"
-            os: windows-2019
+#  build-octave-package:
+#    needs: check-release-consistency
+#    runs-on: ${{ matrix.os }}
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        include:
+#          - name: "Octave Linux"
+#            os: ubuntu-22.04 # required to ease the support of octave ≥ 6
+#            force_update: on
+#          - name: "Octave macOS"
+#            os: macOS-12
+#          - name: "Octave Windows"
+#            os: windows-2019
+#
+#    steps:
+#      - uses: actions/checkout@v2
+#        with:
+#          submodules: 'recursive'
+#
+#      - name: Check tag
+#        shell: bash
+#        run: |
+#          GIT_TAG=${{ needs.check-release-consistency.outputs.git-tag }}
+#          echo "GIT_TAG=${GIT_TAG}" >> $GITHUB_ENV
+#
+#      - name: Define local variables
+#        shell: bash
+#        run: |
+#          echo "MODE=Release"              >> $GITHUB_ENV
+#          echo "ENABLE_PYTHON_BINDING=off" >> $GITHUB_ENV
+#          echo "ENABLE_OCTAVE_BINDING=on"  >> $GITHUB_ENV
+#
+#      - name: Define local variables Unix Like
+#        shell: bash
+#        run: |
+#          echo "BUILD_NAME=linux-macos"    >> $GITHUB_ENV
+#        if: runner.os != 'Windows'
+#
+#      - name: Define local variables Windows
+#        shell: bash
+#        run: |
+#          echo "BUILD_NAME=octave-windows" >> $GITHUB_ENV
+#        if: runner.os == 'Windows'
+#
+#      - name: pre-install-linux
+#        shell: bash
+#        run: |
+#          if [ "${{matrix.force_update}}" == "on" ]; then
+#            sudo apt update
+#          fi
+#          sudo apt install liblapack-dev python3-pip
+#          sudo apt install -qy octave liboctave-dev
+#        if: runner.os == 'Linux' # or use $RUNNER_OS
+#
+#      - name: install
+#        shell: bash
+#        run: .travis-ci/${BUILD_NAME}/install.sh
+#
+#      - name: Setup cmake
+#        uses: jwlawson/actions-setup-cmake@v1.13
+#        with:
+#          cmake-version: '3.24.x'
+#
+#      - name: before_script
+#        shell: bash
+#        run: .travis-ci/common/before_script.sh
+#
+#      - name: script
+#        shell: bash
+#        run: .travis-ci/${BUILD_NAME}/build.sh
+#
+#      - name: test
+#        shell: bash
+#        run: .travis-ci/${BUILD_NAME}/test.sh
+#
+#      - name: make package
+#        shell: bash
+#        run: |
+#          .travis-ci/release/octave-release.sh
+#
+#      - name: Archive build artifacts
+#        uses: actions/upload-artifact@v2
+#        with:
+#          name: octave-package
+#          path: |
+#            octave-package
 
-    steps:
-      - uses: actions/checkout@v2
-        with:
-          submodules: 'recursive'
-
-      - name: Check tag
-        shell: bash
-        run: |
-          GIT_TAG=${{ needs.check-release-consistency.outputs.git-tag }}
-          echo "GIT_TAG=${GIT_TAG}" >> $GITHUB_ENV
-          
-      - name: Define local variables
-        shell: bash
-        run: |
-          echo "MODE=Release"              >> $GITHUB_ENV
-          echo "ENABLE_PYTHON_BINDING=off" >> $GITHUB_ENV
-          echo "ENABLE_OCTAVE_BINDING=on"  >> $GITHUB_ENV
-
-      - name: Define local variables Unix Like
-        shell: bash
-        run: |
-          echo "BUILD_NAME=linux-macos"    >> $GITHUB_ENV
-        if: runner.os != 'Windows'
-
-      - name: Define local variables Windows
-        shell: bash
-        run: |
-          echo "BUILD_NAME=octave-windows" >> $GITHUB_ENV
-        if: runner.os == 'Windows'
-
-      - name: pre-install-linux
-        shell: bash
-        run: |
-          if [ "${{matrix.force_update}}" == "on" ]; then
-            sudo apt update
-          fi
-          sudo apt install liblapack-dev python3-pip
-          sudo apt install -qy octave liboctave-dev
-        if: runner.os == 'Linux' # or use $RUNNER_OS
-
-      - name: install
-        shell: bash
-        run: .travis-ci/${BUILD_NAME}/install.sh
-
-      - name: Setup cmake
-        uses: jwlawson/actions-setup-cmake@v1.13
-        with:
-          cmake-version: '3.24.x'
-
-      - name: before_script
-        shell: bash
-        run: .travis-ci/common/before_script.sh
-
-      - name: script
-        shell: bash
-        run: .travis-ci/${BUILD_NAME}/build.sh
-
-      - name: test
-        shell: bash
-        run: .travis-ci/${BUILD_NAME}/test.sh
-          
-      - name: make package
-        shell: bash
-        run: |
-          .travis-ci/release/octave-release.sh
-                     
-      - name: Archive build artifacts
-        uses: actions/upload-artifact@v2
-        with:
-          name: octave-package
-          path: |
-            octave-package
-
-  build-R-package:
-    needs: check-release-consistency
-    runs-on: ${{ matrix.os }}
-    strategy:
-      fail-fast: false
-      matrix:
-        include:
-          - name: "R Linux"
-            os: ubuntu-20.04
-          - name: "R macOS"
-            os: macOS-12  
-          - name: "R Windows"
-            os: windows-2019
-            
-    steps:
-      - uses: actions/checkout@v2
-        with:
-          submodules: 'recursive'
-
-      - uses: r-lib/actions/setup-r@v2
-        with:
-          r-version: '4.2'
-
-      - name: Check tag
-        shell: bash
-        run: |
-          GIT_TAG=${{ needs.check-release-consistency.outputs.git-tag }}
-          echo "GIT_TAG=${GIT_TAG}" >> $GITHUB_ENV
-
-      - name: Define local variables
-        shell: bash
-        run: |
-          echo "MODE=Release"              >> $GITHUB_ENV
-          echo "ENABLE_PYTHON_BINDING=off" >> $GITHUB_ENV
-          echo "ENABLE_OCTAVE_BINDING=off" >> $GITHUB_ENV
-
-      - name: Define local variables Unix Like
-        shell: bash
-        run: |
-          echo "BUILD_NAME=r-linux-macos"  >> $GITHUB_ENV
-        if: runner.os != 'Windows'
-
-      - name: Define local variables Windows
-        shell: bash
-        run: |
-          echo "BUILD_NAME=r-windows"      >> $GITHUB_ENV
-        if: runner.os == 'Windows'
-
-      - name: pre-install-linux
-        shell: bash
-        run: |
-          if [ "${{matrix.force_update}}" == "on" ]; then
-            sudo apt update
-          fi
-          sudo apt install -qy r-base liblapack-dev gfortran
-        if: runner.os == 'Linux' # or use $RUNNER_OS
-
-      - name: install
-        shell: bash
-        run: .travis-ci/${BUILD_NAME}/install.sh
-
-      - name: Setup cmake
-        uses: jwlawson/actions-setup-cmake@v1.13
-        with:
-          cmake-version: '3.24.x'
-
-      - name: before_script
-        shell: bash
-        run: .travis-ci/common/before_script.sh
-
-      - name: script
-        shell: bash
-        run: .travis-ci/${BUILD_NAME}/build.sh
-
-      - name: test
-        shell: bash
-        run: .travis-ci/${BUILD_NAME}/test.sh
-
-      - name: make package
-        shell: bash
-        run: |
-          .travis-ci/release/r-release.sh
-
-      - name: Archive build artifacts
-        uses: actions/upload-artifact@v2
-        with:
-          name: R-package
-          path: |
-            R-package
+#  build-R-package:
+#    needs: check-release-consistency
+#    runs-on: ${{ matrix.os }}
+#    strategy:
+#      fail-fast: false
+#      matrix:
+#        include:
+#          - name: "R Linux"
+#            os: ubuntu-20.04
+#          - name: "R macOS"
+#            os: macOS-12
+#          - name: "R Windows"
+#            os: windows-2019
+#
+#    steps:
+#      - uses: actions/checkout@v2
+#        with:
+#          submodules: 'recursive'
+#
+#      - uses: r-lib/actions/setup-r@v2
+#        with:
+#          r-version: '4.2'
+#
+#      - name: Check tag
+#        shell: bash
+#        run: |
+#          GIT_TAG=${{ needs.check-release-consistency.outputs.git-tag }}
+#          echo "GIT_TAG=${GIT_TAG}" >> $GITHUB_ENV
+#
+#      - name: Define local variables
+#        shell: bash
+#        run: |
+#          echo "MODE=Release"              >> $GITHUB_ENV
+#          echo "ENABLE_PYTHON_BINDING=off" >> $GITHUB_ENV
+#          echo "ENABLE_OCTAVE_BINDING=off" >> $GITHUB_ENV
+#
+#      - name: Define local variables Unix Like
+#        shell: bash
+#        run: |
+#          echo "BUILD_NAME=r-linux-macos"  >> $GITHUB_ENV
+#        if: runner.os != 'Windows'
+#
+#      - name: Define local variables Windows
+#        shell: bash
+#        run: |
+#          echo "BUILD_NAME=r-windows"      >> $GITHUB_ENV
+#        if: runner.os == 'Windows'
+#
+#      - name: pre-install-linux
+#        shell: bash
+#        run: |
+#          if [ "${{matrix.force_update}}" == "on" ]; then
+#            sudo apt update
+#          fi
+#          sudo apt install -qy r-base liblapack-dev gfortran
+#        if: runner.os == 'Linux' # or use $RUNNER_OS
+#
+#      - name: install
+#        shell: bash
+#        run: .travis-ci/${BUILD_NAME}/install.sh
+#
+#      - name: Setup cmake
+#        uses: jwlawson/actions-setup-cmake@v1.13
+#        with:
+#          cmake-version: '3.24.x'
+#
+#      - name: before_script
+#        shell: bash
+#        run: .travis-ci/common/before_script.sh
+#
+#      - name: script
+#        shell: bash
+#        run: .travis-ci/${BUILD_NAME}/build.sh
+#
+#      - name: test
+#        shell: bash
+#        run: .travis-ci/${BUILD_NAME}/test.sh
+#
+#      - name: make package
+#        shell: bash
+#        run: |
+#          .travis-ci/release/r-release.sh
+#
+#      - name: Archive build artifacts
+#        uses: actions/upload-artifact@v2
+#        with:
+#          name: R-package
+#          path: |
+#            R-package
 
   all-package-build-checkpoint:
     name: Build package checkpoint
     needs:
       - check-release-consistency
       - build-wheel-python
-      - build-R-package
-      - build-octave-package
+#      - build-R-package
+#      - build-octave-package
     runs-on: ubuntu-20.04
     steps:
       - uses: actions/checkout@v2
@@ -431,56 +431,56 @@ jobs:
                   ./dist/*.whl
         if: ${{ needs.check-release-consistency.outputs.draft-release == 'false' }}  
 
-  release-artifacts:
-    name: Upload Release Asset
-    needs:
-      - check-release-consistency
-      - all-package-build-checkpoint
-    runs-on: ubuntu-20.04
-    steps:
-      - uses: actions/checkout@v2
-        with:
-          submodules: false
-
-      - uses: actions/download-artifact@v2
-        with:
-          name: python-artifact
-          path: dist
-        if: ${{ needs.check-release-consistency.outputs.draft-release == 'true' }}
-
-      - uses: actions/download-artifact@v2
-        with:
-          name: octave-package
-          path: dist
-
-      - uses: actions/download-artifact@v2
-        with:
-          name: R-package
-          path: dist
-
-      - name: Check tag
-        shell: bash
-        run: |
-          GIT_TAG=${{ needs.check-release-consistency.outputs.git-tag }}
-          echo "GIT_TAG=${GIT_TAG}" >> $GITHUB_ENV
-
-      - name: upload assets
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        shell: bash
-        run: |
-          set -eo pipefail
-          set -x
-
-          # using https://github.com/github/hub
-          mkdir -p dist
-          assets=()
-          for asset in ./dist/*; do
-            assets+=("-a" "$asset")
-          done
-          if [ "${{ needs.check-release-consistency.outputs.draft-release }}" == "true" ]; then
-            hub release edit -m "Draft Release $GIT_TAG" "${assets[@]}" "$GIT_TAG"          
-          else
-            hub release edit -m "Release $GIT_TAG" "${assets[@]}" "$GIT_TAG"
-          fi
-          
+#  release-artifacts:
+#    name: Upload Release Asset
+#    needs:
+#      - check-release-consistency
+#      - all-package-build-checkpoint
+#    runs-on: ubuntu-20.04
+#    steps:
+#      - uses: actions/checkout@v2
+#        with:
+#          submodules: false
+#
+#      - uses: actions/download-artifact@v2
+#        with:
+#          name: python-artifact
+#          path: dist
+#        if: ${{ needs.check-release-consistency.outputs.draft-release == 'true' }}
+#
+#      - uses: actions/download-artifact@v2
+#        with:
+#          name: octave-package
+#          path: dist
+#
+#      - uses: actions/download-artifact@v2
+#        with:
+#          name: R-package
+#          path: dist
+#
+#      - name: Check tag
+#        shell: bash
+#        run: |
+#          GIT_TAG=${{ needs.check-release-consistency.outputs.git-tag }}
+#          echo "GIT_TAG=${GIT_TAG}" >> $GITHUB_ENV
+#
+#      - name: upload assets
+#        env:
+#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+#        shell: bash
+#        run: |
+#          set -eo pipefail
+#          set -x
+#
+#          # using https://github.com/github/hub
+#          mkdir -p dist
+#          assets=()
+#          for asset in ./dist/*; do
+#            assets+=("-a" "$asset")
+#          done
+#          if [ "${{ needs.check-release-consistency.outputs.draft-release }}" == "true" ]; then
+#            hub release edit -m "Draft Release $GIT_TAG" "${assets[@]}" "$GIT_TAG"
+#          else
+#            hub release edit -m "Release $GIT_TAG" "${assets[@]}" "$GIT_TAG"
+#          fi
+#
